name: Update Dockerhub description

on:
  push:
    branches:
      - 'master'
    paths:
      - 'README.md'
      - '.github/workflows/description.yml'

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: passivelemon
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: passivelemon/terraria-docker
          short-description: ${{ github.event.repository.description }}

