name: Release Publish

on:
  release:
    types: [ published ]

jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Get terraria release
        id: get_terraria_release
        run: |
          TERRARIA="${{ github.event.release.tag_name }}"
          TERRARIAFIX=$(echo \"$TERRARIA\" | jq 'gsub("\\."; "")')
          echo "Latest terraria release is ${TERRARIA}." >> "$GITHUB_STEP_SUMMARY"
          echo "latest_terraria=$TERRARIA" >> "$GITHUB_OUTPUT"
          echo "latest_terraria_fix=$TERRARIAFIX" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker & GHCR
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "passivelemon" --password-stdin
          echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u "passivelemon" --password-stdin

      - name: Build the image
        run: |
          docker buildx create --name mainbuilder --driver docker-container --platform linux/amd64 --use

          docker buildx build --push \
            --build-arg TERRARIAVERSION=${{ steps.get_terraria_release.outputs.latest_terraria }} \
            --build-arg TERRARIAVERSIONFIX=${{ steps.get_terraria_release.outputs.latest_terraria_fix }} \
            --provenance=false \
            --platform linux/amd64,linux/arm64 \
            --tag passivelemon/terraria-docker:${{ steps.get_terraria_release.outputs.latest_terraria }} \
            --tag passivelemon/terraria-docker:latest \
            --tag ghcr.io/passivelemon/terraria-docker:${{ steps.get_terraria_release.outputs.latest_terraria }} \
            --tag ghcr.io/passivelemon/terraria-docker:latest \
            .

