name: (Terraria) Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Terraria version'
        required: true
        type: string
      version_trim:
        description: 'Terraria version trimmed'
        required: true
        type: string
    
  workflow_call:
    inputs:
      version:
        description: 'Terraria version'
        required: true
        type: string
      version_trim:
        description: 'Terraria version trimmed'
        required: true
        type: string

jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: passivelemon
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./terraria
          push: true
          platforms: linux/amd64
          build-args: |
            VERSION=${{ github.event.inputs.version }}
            VERSIONTRIM=${{ github.event.inputs.version_trim }}
          tags: |
            passivelemon/terraria-docker:latest
            passivelemon/terraria-docker:terraria-latest
            passivelemon/terraria-docker:terraria-${{ github.event.inputs.version }}
            ghcr.io/passivelemon/terraria-docker:latest
            ghcr.io/passivelemon/terraria-docker:terraria-latest
            ghcr.io/passivelemon/terraria-docker:terraria-${{ github.event.inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

