name: Release Publish

on:
  release:
    types: [ published ]

jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get terraria release
        id: get_terraria_release
        run: |
          TERRARIA="1.4.4.9"
          TERRARIAFIX=$(echo \"$TERRARIA\" | jq 'gsub("\\."; "")')
          echo "Latest Terraria release is ${TERRARIA}." >> "$GITHUB_STEP_SUMMARY"
          echo "latest_terraria=$TERRARIA" >> "$GITHUB_OUTPUT"
          echo "latest_terraria_fix=$TERRARIAFIX" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: passivelemon
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./terraria
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            TERRARIAVERSION=1.4.4.9
            TERRARIAVERSIONFIX=1449
          tags: |
            passivelemon/terraria-docker:terraria-latest
            passivelemon/terraria-docker:terraria-1.4.4.9
            ghcr.io/passivelemon/terraria-docker:terraria-latest
            ghcr.io/passivelemon/terraria-docker:terraria-1.4.4.9
          cache-from: type=gha
          cache-to: type=gha,mode=max

