name: (tModLoader) Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'tModLoader version'
        required: true
        type: string
      year:
        description: 'Release year'
        required: true
        type: string
      type:
        description: 'If the release is a pre-release'
        required: true
        type: string
    
  workflow_call:
    inputs:
      version:
        description: 'tModLoader version'
        required: true
        type: string
      year:
        description: 'Release year'
        required: true
        type: string
      type:
        description: 'If the release is a pre-release'
        required: true
        type: string

jobs:
  setup-build-push:
    if: ${{ inputs.version != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: passivelemon
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push Docker image (Pre-release)
        uses: docker/build-push-action@v6
        if: ${{ inputs.type == 'prerelease' }}
        with:
          context: ./tmodloader
          push: true
          platforms: linux/amd64
          build-args: VERSION=${{ inputs.version }}
          tags: |
            passivelemon/terraria-docker:tmodloader-latest-pre
            passivelemon/terraria-docker:tmodloader-${{ inputs.year }}-pre
            passivelemon/terraria-docker:tmodloader-${{ inputs.version }}
            ghcr.io/passivelemon/terraria-docker:tmodloader-latest-pre
            ghcr.io/passivelemon/terraria-docker:tmodloader-${{ inputs.year }}-pre
            ghcr.io/passivelemon/terraria-docker:tmodloader-${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (Release)
        uses: docker/build-push-action@v6
        if: ${{ inputs.type == 'release' }}
        with:
          context: ./tmodloader
          push: true
          platforms: linux/amd64
          build-args: VERSION=${{ inputs.version }}
          tags: |
            passivelemon/terraria-docker:tmodloader-latest
            passivelemon/terraria-docker:tmodloader-${{ inputs.year }}
            passivelemon/terraria-docker:tmodloader-${{ inputs.version }}
            ghcr.io/passivelemon/terraria-docker:tmodloader-latest
            ghcr.io/passivelemon/terraria-docker:tmodloader-${{ inputs.year }}
            ghcr.io/passivelemon/terraria-docker:tmodloader-${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

